// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdOZnJsBmRB1B7hiKkvaot1-SI1_Zj-FA',
    appId: '1:731877536655:web:0e370fc94221618f0751fa',
    messagingSenderId: '731877536655',
    projectId: 'chat-app-57acd',
    authDomain: 'chat-app-57acd.firebaseapp.com',
    storageBucket: 'chat-app-57acd.firebasestorage.app',
    measurementId: 'G-X1XX81SLXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyWZ7tSKzaN3-YiGt9Qqs-MgmBGSZBPA4',
    appId: '1:731877536655:android:0c115e4c5acd6c130751fa',
    messagingSenderId: '731877536655',
    projectId: 'chat-app-57acd',
    storageBucket: 'chat-app-57acd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUGgNUaq3JcL8iPfUP8CZgzKqfLBDmo-w',
    appId: '1:731877536655:ios:9427ad9cf819c1160751fa',
    messagingSenderId: '731877536655',
    projectId: 'chat-app-57acd',
    storageBucket: 'chat-app-57acd.firebasestorage.app',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUGgNUaq3JcL8iPfUP8CZgzKqfLBDmo-w',
    appId: '1:731877536655:ios:9427ad9cf819c1160751fa',
    messagingSenderId: '731877536655',
    projectId: 'chat-app-57acd',
    storageBucket: 'chat-app-57acd.firebasestorage.app',
    iosBundleId: 'com.example.chatApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdOZnJsBmRB1B7hiKkvaot1-SI1_Zj-FA',
    appId: '1:731877536655:web:510fa0e8627c84460751fa',
    messagingSenderId: '731877536655',
    projectId: 'chat-app-57acd',
    authDomain: 'chat-app-57acd.firebaseapp.com',
    storageBucket: 'chat-app-57acd.firebasestorage.app',
    measurementId: 'G-G99QRG9187',
  );
}
